name: hitchhike
description: A new Mobile application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.0
  rxdart: ^0.24.0
  meta: ^1.1.8
  flutter_bloc: 6.1.2
  shared_preferences: ^0.5.12+4
  dio: ^3.0.10
  equatable: ^1.2.6
  google_sign_in: ^4.5.4
  flutter_facebook_auth: "^1.0.0"
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.1
  cloud_firestore: ^0.16.0+1
  
  # Add the dependency for the FlutterFire plugin for Google Analytics
  font_awesome_flutter: ^8.4.0
  graphql: ^4.0.0-beta
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  build_runner: ^1.0.0

flutter_icons:
  image_path: "assets/icons/ic_launcher.png"
  android: true
  ios: true


# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/